// <auto-generated />
using Magals.DevicesControl.DbContext.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplicationGenMigrations.Migrations
{
    [DbContext(typeof(SettingsDevicesDbContext))]
    [Migration("20231122121850_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("settingsdevices")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.ConfigsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Autoscan")
                        .HasColumnType("boolean");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingsDevicesEntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type_Connect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SettingsDevicesEntityName");

                    b.ToTable("ConfigEntities", "settingsdevices");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.CustomsettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConfigsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigsId");

                    b.ToTable("CustomsettingsEntities", "settingsdevices");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.SettingsDevicesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SettingsDevicesEntities", "settingsdevices");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.ConfigsEntity", b =>
                {
                    b.HasOne("Magals.DevicesControl.DbContext.Entities.SettingsDevicesEntity", "SettingsDevicesEntity")
                        .WithMany("Configs")
                        .HasForeignKey("SettingsDevicesEntityName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettingsDevicesEntity");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.CustomsettingsEntity", b =>
                {
                    b.HasOne("Magals.DevicesControl.DbContext.Entities.ConfigsEntity", "Configs")
                        .WithMany("Customsettings")
                        .HasForeignKey("ConfigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configs");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.ConfigsEntity", b =>
                {
                    b.Navigation("Customsettings");
                });

            modelBuilder.Entity("Magals.DevicesControl.DbContext.Entities.SettingsDevicesEntity", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
